print('Testando alguns comandos de python !')
print('Iremos criar uma variavel com o nome z1 para receber alguma informação z1 =input(Digite algo :)')
z1 =input('Digite algo :')
print('O tipo primitivo desse valor é',z1,  type (z1))
print('Só tem espaços', z1.isspace())
print('É numérico', z1.isnumeric())
print('É alfabetico?', z1.isalpha())
print('É alfanumérico?', z1.isalnum())
print('Está em maiúscolas?', z1.isupper())
print('Comando islower Está em minusculas? ', z1.islower())
print('Está captalizada?', z1.capitalize())
print('Cada função tem sua tarefa a baixo veremos alguns exemplos:')
